# Generated by Django 5.1.3 on 2024-12-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='code',
        ),
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
