# Generated by Django 5.1.3 on 2024-12-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0006_customers_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
