# Generated by Django 5.1.3 on 2024-12-05 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0008_remove_customers_code_customers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254' followed by 9 digits.", regex='^\\+254\\d{9}$')]),
        ),
    ]
