name: Backend CI Workflow

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r service/requirements.txt
      - name: Write .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run Tests
        env:
          ENV_FILE: .env
        run: |
          source venv/bin/activate
          cd service
          python3 manage.py test --keepdb --verbosity=2
      - name: Lint Code
        run: |
          source venv/bin/activate
          flake8 .  
